version: '3.8'

services:
  load_balancer1:
    image: us-central1-docker.pkg.dev/triple-throttlers-446213/nginx/crdt1:latest
    ports:
      - target: 8080
        published: 8090
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == loadbalancer1

  load_balancer2:
    image: us-central1-docker.pkg.dev/triple-throttlers-446213/nginx/crdt2:latest
    ports:
      - target: 8080
        published: 8091
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == loadbalancer2

  redis-enterprise-1:
    image: redislabs/redis:latest
    cap_add:
      - sys_resource
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host  
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
      - target: 12000
        published: 12000
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.hostname==loadbalancer1

  redis-enterprise-2:
    image: redislabs/redis:latest
    cap_add:
      - sys_resource
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
      - target: 12000
        published: 12000
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.hostname==loadbalancer2

  db:
    image: descartesresearch/teastore-db
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  registry:
    image: descartesresearch/teastore-registry
    ports:
      - target: 8080
        published: 8083
        protocol: tcp
        mode: host
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  persistence:
    image: descartesresearch/teastore-persistence
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  auth:
    image: descartesresearch/teastore-auth
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  image:
    image: descartesresearch/teastore-image
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  recommender:
    image: descartesresearch/teastore-recommender
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  webui:
    image: descartesresearch/teastore-webui
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

volumes:
  mysql_data:

networks:
  default:
    driver: overlay
    name: teastore-network
