version: '3.8'

services:
  load_balancer1:
    image: us-central1-docker.pkg.dev/triple-throttlers-446213/nginx/nginx:latest
    build:
      context: ./nginx
    ports:
      - "8090:8080"
    deploy:
      placement:
        constraints:
          - node.labels.type == loadbalancer1

  load_balancer2:
    image: us-central1-docker.pkg.dev/triple-throttlers-446213/nginx/nginx:latest
    build:
      context: ./nginx
    ports:
      - "8091:8080"
    deploy:
      placement:
        constraints:
          - node.labels.type == loadbalancer2

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    deploy:
      placement:
        constraints:
          - node.labels.type == database

  mysql:
    image: mysql:8.4
    ports:
      - "3306:3306"
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rate_limit_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    deploy:
      placement:
        constraints:
          - node.labels.type == database

  registry:
    image: descartesresearch/teastore-registry
    ports:
      - "8083:8080"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  db: 
    image: descartesresearch/teastore-db
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  persistence:
    image: descartesresearch/teastore-persistence
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  auth:
    image: descartesresearch/teastore-auth
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  image:
    image: descartesresearch/teastore-image
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  recommender:
    image: descartesresearch/teastore-recommender
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

  webui:
    image: descartesresearch/teastore-webui
    ports:
      - "8080:8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    deploy:
      placement:
        constraints:
          - node.labels.type == teastore

volumes:
  mysql_data:

networks:
  default:
    driver: overlay
    name: teastore-network